- config/story.json
It adds the Taboola Recommendations zone to story pages when configured.
It also removes the featured-carousel zone which is no longer in use, and wasn't configured properly to boot.
**Jira link:** https://jira.mcclatchyinteractive.com/browse/PEX-38
1. Start a local webserver in the zones directory
2. Go to this article in Chrome: https://www.kansascity.com/living/travel/article276767036.html
3. In the sources tab, make sure Enable Overrides is checked
4. Find the `article276767036.html` file, right click and select "Save for Overrides" and open it
5. Find the `netdale.[hash].js file`, right click and select "Save for Overrides"
6. In the article file, add the following right above line 63 that freezes the `window.pageInfo` object and save it
``` …
```
> Taboola recommendations

- config/section.json
It removes the Amazon Prime Day card from the section configuration.
1. Fire up a local server from the main zones repo directory in the new branch
2. Go to any of our shopping pages (https://www.kansas.com/shopping)
3. Open up netdale.xxx.js in DevTools and save for overrides
4. Search for the string `section.json`
5. Replace `/static/hi/zones/section.json` with `http://localhost:3000/config/section.json`
6. Reload the webpage and see if it's still there.
> remove amazon prime day zone from sections

- index.js
It updates the cadence/frequency of zone placements on story pages for non-subscribers to 2 as opposed to 3. This is more specifically part of a test by the ad team with the purpose of gathering data on ad impressions over a 48 hour period. 
1. Go to any of our story pages
2. Open up netdale.xxx.js in DevTools and save for overrides
3. Search for the string `4 : 3`
4. Replace `4 : 3` with `4 : 2`
5. Reload the webpage and check that the zones show up every 2 paragraphs.
PS: The above steps do not directly test from the new feature branch. A proper test would require a rebuild of the netdale file, which I do not have the resources for. There is only one character change in this update, so it's very straightforward. Please let me know if there are any questions.
> change zone distribution cadence for non-subscribers to 2

- config/story.json
- demo/locker.js
**_This should only be released after Zones 1.5.0 is in production._**
Adds two new CUE zones to the story config:
- siTickets = an iframe from Sports Illustrated for Gamecocks tickets
- gamecocksNav = section navigation for article pages
1. Fire up a local server of the repo on 3000
2. Go to the demo story page (http://localhost:3000/demo/story/)
3. Replace the `story.json` file with [this version](https://raw.githubusercontent.com/mcclatchy/zones/677ba736cadd826e479cd3b0b5e61004ab6b6283/config/story.json) from the PR.
4. Reload the page and confirm:
- the new siTickets zone is rendering above `zone-el-101`
- the new gamecocksNav zone is rendering above `.story-body`
> New siTickets and gamecocksNav zones

- config/story.json
- demo/demo.css
- demo/locker.js
- demo/section/index.html
It adds a new zone tied to a `zone.sponsoredArticle` section config that renders the words "SPONSORED CONTENT" above the `.header` element. It uses CSS to do this, and the payload is stored in CUE.
This is a replication of an Article Widget 1 concept, but better. I also reset the local `locker.js` file to hide some previous customizations, and remove some dead ones. Lastly, I also changed the demo CSS a bit to make the zones smaller by default on story pages.
I'm adding a hidden class on this zone because it's CSS only. The `demo.css` file is forcing the block display so we can confirm it's working. The zone should collapse in production. If it doesn't I'll adjust.
1. Pull down the branch.
2. Fire up your local server and go to the [story page](http://localhost:3000/demo/story/)
> adding sponsored article disclaimer zone

- config/story.json
- demo/locker.js
- demo/story/index.html
- lib/config.js
- lib/zones.js
- package.json
It adds Amplitude tracking capabilities to zones. To enable in the configuration layer, simply add `"tracking": true` to any zone. 
We should not add tracking to standard zones. The Performance Team already has this functionality. Only use this for custom zones like `zone-taboola-recommendations`.
1. Pull down the feature branch and fire up your local server.
2. Load the [story page](http://localhost:3000/demo/story/) and open DevTools.
3. Scroll down to the `zone-taboola-recommendations` zone.
4. Check in Devtools for the following line.
```
zone tracked: {"data":[{"zone":"taboola-recommendations","action":"impression","count":1}]}
```
This is a live test using Overrides and an Amplitude Chrome Extension to verify the `$exposure` event fired.
1. Install the [Amplitude Event …
> Zone tracking

- config/story.json
It adds a local recirculation digest using the [custom-digest](https://mcclatchy.github.io/cards/custom-digest/) card after `zone-el-101` for in-market readers and subscribers.
1. Download this [overrides.zip](https://github.com/mcclatchy/zones/files/12501375/overrides.zip) file and unzip it into your local overrides folder.
2. Go to [this arcitle](https://www.bnd.com/article278861404.html) on bnd.com, enable overrides and make sure you're logged in as a subscriber.
> adding local news digest to stories

- config/story.json
- demo/locker.js
- index.js
- lib/config.js
- package.json
It moves the cadence logic into the config.js file, allowing us to pass it in through the config json files. It also cleans up the index.js file a bit to match.
_Note: the test of setting the cadence to two for out-of-market readers passed and Nick wanted to scale that out. This release also remove the test filters._
1. Fire up the demo on a local server and go to the [story page](http://localhost:3000/demo/story/).
2. Open the `demo/locker.js` file and alter the return values for the `user.isSubscriber()` and `user.isInDMA()` functions to see the different cadence. The values should be 4 for subscribers, 3 for dma, and 2 for everyone else.
> Config cadence

- demo/story/index.html
- index.js
- lib/config.js
QA does not have the bucket synced like production, and we were not properly rejecting our promise in that environment. This update adds that so the performance team can pick up on it and make a decision about what to do.
> rejecting config.load on error

- config/story.json
- demo/locker.js
It adds the Sotheby's sponsorship messaging back to all stories desked to Lexgo Eat and all child sections. This was previously done with the Article Widget 1 grouping, and needed to be moved into zones since we lost that capability.
1. Dowload [lexgoeat-sponsor-overrides.zip](https://github.com/mcclatchy/zones/files/12611787/lexgoeat-sponsor-overrides.zip) and unzip into your local overrides folder and make sure they are enabled.
2. Go to [any story](https://www.kentucky.com/lexgoeat/food/article279279859.html) in Lexgo Eat or any child section. 
3. The zone should appear above the story (section config already added).
> adding lexgo eat sponsor to story pages

- config/homepage.json
- config/section.json
- config/story.json
- demo/demo.css
- demo/homepage/index.html
- demo/locker.js
- demo/section/index.html
- demo/story/index.html
- index.js
- lib/config.js
- lib/zones.js
This is a different sort of thing that what we've been doing. Instead of reviewing a specifc workflow for specific output, how do you feel about just messing with the configs a bit locally to see how they feel? This will not merge into main. I've created a new `rc-v2` branch to gather all the updates for the next version.
I've got you both on here for feedback, and am simply looking for a thumbs up meaning "good enough for now let's proceed," or a chat about how we'd like to change it. There will be more changes down the line.
*Side note Julia, I was able to pick the branch I want this to merge into when making this PR.*
> config structure simplification

- config/homepage.json
- config/section.json
- config/story.json
- demo/ads.js
- demo/demo.css
- demo/homepage/index.html
- demo/locker.js
- demo/saratoga.css
- demo/story/index.html
- index.js
- lib/config.js
- lib/zones.js
- package.json
It includes the simplified config structure and preliminary code to generate ad units from the extension. The ad functionality is not enabled. It also adds some additional functionality.
+ We can now set the position for the injection point. Values will be passed directly into the `insertAdjacentHTML()` function as the first argument, and should therefore be one of the supported values.
+ `style` is now hooked up and configurable using a standard inline CSS string
+ `type` is now configurable and will be passed to the `data-type` attribute. We will use this later for ads, and SDS also has values for this attribute. It's an open string, but current values are "ad" and "editorial".
+ cue and zephr payloads are lazy-loaded by an intersection observer. HTL ad tags, when we implement those, …
> New config structure

- config/section.json
Bringing back the Amazone Prime Day card for Black Friday sales. This zone only applies to shopping section pages.
Note: there is a sister PR in the cards repo to update the design a bit and that is also included in the overrides file.
[black-friday-overrides.zip](https://github.com/mcclatchy/zones/files/13383412/black-friday-overrides.zip)
> bringing back the amazon-prime-day card for black friday

- config/section.json
Chase asked for this one to come down. Simple config removal in the `section.json` file.
> PEX-63: removing amazon prime section zone

- config/story.json
Cynthia asked to put the Taboola recommendations zone on all stories for all markets. This simply removes the filter in the config.
> PEX-62: putting Taboola recommendations on all stories

- demo/story/index.html
- index.js
Joe W. identified an issue where we were clobbering the `window.mi.zones` object. We are moving in the direction of having the extension manage all data associated with zones, but I jumped the gun a bit and Joe still needs this object. This change simply ensures if there is already a `window.mi.zones` object in play to extend it.
I've changed the [story demo page](http://localhost:3000/demo/story/) to set the `window.mi` object up prior to loading the extension. You can see the additional `test: "performance"` property/value in devtools.
> ensuring mi.zones isn't clobbered

- config/story.json
- package.json
This removes the Sports Illustrated ticket zone from the article config. 
We're removing it because football season is over and SI hasn't yet provided reliable API endpoints for basketball events. We'll reactivate this zone once they provide functional performer IDs for additional sports. 
[Remind me if this needs a version bump of some sort. The change is config-only so I didn't add it to the PR.]
> Remove the SI Tickets widget (awaiting SI updates)

- config/story.json
Round two enabling Taboola recirc modules on all stories, all markets.
> PE-72: putting Taboola recirc on all stories

- config/story.json
- index.js
It adds the value of `locker.getYozonsLocker("core").areAdsAllowed()` to the config Set, just like the DMA function.
_Note: there is an updated `story.json` file to use this in the attached overrides zip._
Unzip the attached overrides folder to your local setup and check out any miamiherald.com article. For dev, I was using this one: https://www.miamiherald.com/sports/nfl/miami-dolphins/article282580408.html
[PE-74-overrides.zip](https://github.com/mcclatchy/zones/files/13641875/PE-74-overrides.zip)
We are not responsible for the look on this one. Taboola renders it and it should look like the attached screenshot.
---
> PE-74: adding the ads allowed config value

- config/homepage.json
Adds two new CUE zones to the homepage config:
- eeditionPromoSections = the eedition promo that features special eedition sections
- eeditionPromoGames = the eedition promo that features the games section
Notes:
- The zones are configured to load CUE HTML items that load the two new cards:
- `/static/hi/cards/v1/eedition-promo/eedition-promo-sections.js`
- `/static/hi/cards/v1/eedition-promo/eedition-promo-games.js`
- There are open help desk tickets to add the relevant pageInfo section configs to each site:
- The sections version will run on FortWorth, Boise, and Belleville
- The games version will run on Charlotte, Tacoma, and State College
1. Go to a homepage ([https://www.bnd.com/](https://www.bnd.com/))
2. Override the [corresponding homepage config …
> Zones for games/sections eedition promos

- config/homepage.json
We've been asked to enable the games/puzzles version of the eedition promo on all sites – this PR removes the alternative "sections" version of the eedition promo from the homepage config. 
This change should be deployed before the section parameter for the "games" version (`mi.pageInfo.zone.eeditionPromoGames`) is added across the board.
> Remove eedition/sections promo from homepage config

- config/story.json
Could you give this a quick once-over and make sure the element is rendering correctly for you. We've been going back and forth with Taboola for a few weeks and it looks like they've got it squared away. Just download the overrides and go to this story (or any other long enough for two zones).
https://www.kansascity.com/sports/spt-columns-blogs/sam-mcdowell/article284558505.html
[PE-88-overrides.zip](https://github.com/mcclatchy/zones/files/14027120/PE-88-overrides.zip)
Here's a screenshot of what you should see, though you will have different stories.
> PE-88: adding taboola recs back

- lib/config.js
- lib/zones.js
This alters the VIP rules for out of market non-subs by including paragraphs, media element and embeds and removing the validity checks. We're doing this to make up for a revenue shortage.
I'm including Yozons overrides and also this [miamiherald article](https://www.miamiherald.com/news/state/florida/article287351770.html), where I've altered the `pageInfo` object to disable the paywall. You should be out of market and can log in to see both experiences.
[PE-127-overrides.zip](https://github.com/mcclatchy/zones/files/15237848/PE-127-overrides.zip)
> PE-127 disable VIP for OOM readers
